version: "2.4"

services:
  gateway-postfix:
    env_file:
      - ./.env
    build: ./build/postfix
    image: mailcow-gateway-postfix:0.3
    networks:
      mailcow-network:
        aliases:
          - gateway-postfix #can add aliases but not change this one, wireguard container relies on this to resolve ip for iptables

  gateway-vpn:
    env_file:
      - ./.env
    build: ./build/wireguard
    image: mailcow-gateway-wireguard:0.3
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf
    ports:
        #default: - 51820:51820/udp
      - "${GATEWAY_WG_PORT:-51820}:51820/udp" #doesn't work without /udp https://github.com/moby/moby/issues/15127
    cap_add:
      - NET_ADMIN
    networks:
      mailcow-network:
        aliases:
          - gateway-vpn

networks:
  mailcow-network:
    name: ${MAILCOW_NETWORK_NAME}
    external: true